# Generated by Django 5.1.1 on 2024-10-25 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processes_number', models.CharField(max_length=250)),
                ('advocate_current', models.CharField(max_length=250)),
                ('advocate_new', models.CharField(max_length=250)),
                ('reason', models.TextField(help_text='Insira os motivos que justificaram a necessidade do substabelecimento.', max_length=250)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
