# Generated by Django 5.1.1 on 2024-11-03 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assisteds', '0004_alter_assistedsmodel_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assisteddocumentmodel',
            name='id_assisted',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_assisteds', to='assisteds.assistedsmodel'),
        ),
    ]
