# Generated by Django 5.1.1 on 2024-10-24 12:32

import django.db.models.deletion
import processes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assisteds', '0001_initial'),
        ('cooperators', '0001_initial'),
        ('requireds', '0001_initial'),
        ('responsibles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(blank=True, default='0', max_length=200, null=True)),
                ('facts', models.TextField(blank=True, help_text='Insira os fatos, narrativa ou detalhes relevantes...', null=True, verbose_name='Fatos / Narrativa')),
                ('number_process', models.CharField(blank=True, max_length=200, null=True)),
                ('jurisdiction', models.CharField(blank=True, choices=[('SOBRADINHO', 'SOBRADINHO')], default='SOBRADINHO', max_length=200, null=True)),
                ('processes_matter', models.CharField(blank=True, max_length=200, null=True)),
                ('processes_classs', models.CharField(blank=True, max_length=200, null=True)),
                ('processes_subject', models.CharField(blank=True, max_length=200, null=True)),
                ('phase', models.CharField(blank=True, choices=[('EM ANÁLISE', 'EM ANÁLISE'), ('PETIÇÃO', 'PETIÇÃO'), ('PROTOCOLADO', 'PROTOCOLADO'), ('FASE PROCESSUAL', 'FASE PROCESSUAL'), ('SENTENÇA', 'SENTENÇA'), ('ENCERRADO', 'ENCERRADO')], max_length=200, null=True)),
                ('date_at', models.DateField(blank=True, null=True)),
                ('status_service', models.CharField(blank=True, default='0', max_length=1, null=True)),
                ('notes', models.IntegerField(blank=True, default=0, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('id_advocate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cooperators.cooperatorsmodel')),
                ('id_assisted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='assisteds.assistedsmodel')),
                ('id_required', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='requireds.requiredsmodel')),
                ('id_responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='responsibles.responsiblesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessDocumentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('bens', 'Bens'), ('casamento', 'Casamento'), ('conta', 'Conta Bancária'), ('cpf', 'CPF'), ('dependentes', 'Dependentes'), ('filhos', 'Filhos'), ('nis', 'NIS'), ('obito', 'Óbito'), ('rendimentos', 'Rendimentos'), ('residencia', 'Comprovante de Residência'), ('reu', 'Réu'), ('rg', 'RG'), ('testemunhas', 'Testemunhas'), ('outro', 'Outros Documentos')], default='outro', max_length=100)),
                ('name_customize', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(upload_to=processes.models.documento_upload_to)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('id_process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents_processes', to='processes.processesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessesNotesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('note', models.TextField(max_length=500)),
                ('user', models.CharField(max_length=250)),
                ('priority', models.CharField(choices=[('Baixa', 'Baixa'), ('Média', 'Média'), ('Alta', 'Alta')], max_length=200)),
                ('date_at', models.CharField(max_length=100)),
                ('time_at', models.CharField(max_length=20)),
                ('status', models.CharField(blank=True, default=0, max_length=1, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('id_process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='note_process', to='processes.processesmodel')),
            ],
        ),
    ]
