# Generated by Django 5.1.1 on 2024-10-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('note', models.TextField(max_length=500)),
                ('user', models.CharField(max_length=250)),
                ('priority', models.CharField(choices=[('Baixa', 'Baixa'), ('Média', 'Média'), ('Alta', 'Alta')], max_length=200)),
                ('date_at', models.CharField(max_length=100)),
                ('time_at', models.CharField(max_length=20)),
                ('status', models.CharField(blank=True, default=0, max_length=1, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
