# Generated by Django 5.1.1 on 2024-10-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperatorsmodel',
            name='decree',
            field=models.CharField(default=0, max_length=250),
        ),
        migrations.AddField(
            model_name='cooperatorsmodel',
            name='registration',
            field=models.CharField(default=0, max_length=250),
        ),
        migrations.AlterField(
            model_name='cooperatorsmodel',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
