# Generated by Django 5.1.1 on 2024-10-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperators', '0002_cooperatorsmodel_decree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperatorsmodel',
            name='decree',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cooperatorsmodel',
            name='registration',
            field=models.CharField(max_length=250),
        ),
    ]
