# Generated by Django 5.1.1 on 2024-10-25 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperators', '0004_remove_cooperatorsmodel_decree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperatorsmodel',
            name='post',
            field=models.CharField(choices=[('Advogado(a)', 'Advogado(a)'), ('Recepicionista', 'Recepicionista'), ('Procurador(a)', 'Procurador(a)')], max_length=200),
        ),
    ]
