# Generated by Django 5.1.1 on 2024-10-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperators', '0005_alter_cooperatorsmodel_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperatorsmodel',
            name='post',
            field=models.CharField(choices=[('Admistrador(a)', 'Admistrador(a)'), ('Advogado(a)', 'Advogado(a)'), ('Recepção', 'Recepção'), ('Procurador(a)', 'Procurador(a)')], max_length=200),
        ),
    ]
