# Generated by Django 5.1.1 on 2024-10-24 12:32

import django.db.models.deletion
import responsibles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assisteds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsiblesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kin', models.CharField(blank=True, choices=[('Pai', 'Pai'), ('Mãe', 'Mãe'), ('Irmão(a)', 'Irmão(a)'), ('Tio(a)', 'Tio(a)'), ('Avô(a)', 'Avô(a)'), ('Outro', 'Outro')], max_length=200)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('status_civil', models.CharField(blank=True, max_length=200, null=True)),
                ('nis', models.CharField(blank=True, max_length=200, null=True)),
                ('rg', models.CharField(blank=True, max_length=200, null=True)),
                ('organ', models.CharField(blank=True, max_length=200, null=True)),
                ('date_birth', models.CharField(blank=True, max_length=200, null=True)),
                ('date_expedition', models.CharField(blank=True, max_length=200, null=True)),
                ('cpf', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('fone_1', models.CharField(blank=True, max_length=200, null=True)),
                ('fone_2', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('district', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('uf', models.CharField(choices=[('ACRE', 'AC'), ('ALAGOAS', 'AL'), ('AMAPÁ', 'AP'), ('AMAZONAS', 'AM'), ('BAHIA', 'BA'), ('CEARÁ', 'CE'), ('ESPÍRITO SANTO', 'ES'), ('GOIÁS', 'GO'), ('MARANHÃO', 'MA'), ('MATO GROSSO', 'MT'), ('MATO GROSSO DO SUL', 'MS'), ('MINAS GERAIS', 'MG'), ('PARÁ', 'PA'), ('PARAÍBA', 'PB'), ('PARANÁ', 'PR'), ('PERNAMBUCO', 'PE'), ('PIAUÍ', 'PI'), ('RIO DE JANEIRO', 'RJ'), ('RIO GRANDE DO NORTE', 'RN'), ('RIO GRANDE DO SUL', 'RS'), ('RONDÔNIA', 'RO'), ('RORAIMA', 'RR'), ('SANTA CATARINA', 'SC'), ('SÃO PAULO', 'SP'), ('SERGIPE', 'SE'), ('TOCANTINS', 'TO')], default='BAHIA', max_length=200, null=True)),
                ('dad', models.CharField(blank=True, max_length=200, null=True)),
                ('mother', models.CharField(blank=True, max_length=200, null=True)),
                ('employee', models.CharField(blank=True, choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], max_length=200, null=True)),
                ('salary', models.CharField(blank=True, max_length=200, null=True)),
                ('other_income', models.CharField(blank=True, max_length=200, null=True)),
                ('dependents', models.CharField(blank=True, max_length=200, null=True)),
                ('house', models.CharField(blank=True, choices=[('Própria', 'Própria'), ('Cedida', 'Cedida'), ('Alugada', 'Alugada')], max_length=200)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('id_assisted', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assisteds.assistedsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsiblesDocumentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('bens', 'Bens'), ('casamento', 'Casamento'), ('conta', 'Conta Bancária'), ('cpf', 'CPF'), ('dependentes', 'Dependentes'), ('filhos', 'Filhos'), ('nis', 'NIS'), ('obito', 'Óbito'), ('rendimentos', 'Rendimentos'), ('residencia', 'Comprovante de Residência'), ('reu', 'Réu'), ('rg', 'RG'), ('testemunhas', 'Testemunhas'), ('outro', 'Outros Documentos')], default='outro', max_length=100)),
                ('name_customize', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(upload_to=responsibles.models.documento_upload_to)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('id_responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents_responsibles', to='responsibles.responsiblesmodel')),
            ],
        ),
    ]
