# Generated by Django 5.1.1 on 2024-10-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsibles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsiblesmodel',
            name='kin',
            field=models.CharField(blank=True, choices=[('Genitor', 'Genitor'), ('Genitora', 'Genitora'), ('Irmão(a)', 'Irmão(a)'), ('Tio(a)', 'Tio(a)'), ('Avô(a)', 'Avô(a)'), ('Outro', 'Outro')], max_length=200),
        ),
    ]
