# Generated by Django 5.1.1 on 2024-10-24 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assisteds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(blank=True, max_length=250, null=True)),
                ('date_at', models.DateField(blank=True, null=True)),
                ('time_at', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(default='0', max_length=1)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('id_assisted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='assisteds.assistedsmodel')),
            ],
        ),
    ]
